//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValheimToDo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValheimToDo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons,Header,,,,
        ///&gt;Clubs,Header,,,,
        ///&gt;&gt;Club,6 Wood,,,
        ///&gt;&gt;Bronze Mace,4 Wood,8 Bronze,3 Leather scraps,,
        ///&gt;&gt;Iron Mace,4 Wood,20 Iron,3 Leather scraps,,
        ///&gt;&gt;Porcupine,5 Fine wood,20 Iron,5 Needle,10 Linen thread,
        ///&gt;&gt;Frostner,10 Ancient bark,30 Silver,5 Ymir flesh,5 Freeze gland,
        ///&gt;&gt;Stagbreaker,20 Core wood,5 Deer trophy,2 Leather scraps,,
        ///&gt;&gt;Iron Sledge,10 Ancient bark,30 Iron,4 Ymir flesh,1 Draugr Elite trophy,
        ///&gt;Combat Axes,Header,,,,
        ///&gt;&gt;Battleaxe,30 Ancient bark,35 Iron,4 Leather scraps,,
        ///&gt;Knives,Header, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValheimData {
            get {
                return ResourceManager.GetString("ValheimData", resourceCulture);
            }
        }
    }
}
